export const TableData: Array<any> = [
{"cargo": "Instructor", "name": "Christian Camilo Aparicio Baquen", "intereses": "Seguridad en IoT, criptografía cuántica, gestión de incidentes de seguridad, Ethical Hacking, computación forense."},
{"cargo": "Instructor", "name": "Christian F. Ariza Porras", "intereses": "Big Data, Linked Data, Semantic Web, Social Search"},
{"cargo": "Profesor Asistente", "name": "Óscar Ávila Cifuentes", "intereses": "Planificación estratégica de TI, Arquitictura empresarial, Diseño y desarrollo de Sistemas de Información"},
{"cargo": "Profesor Asociado", "name": "Germán Bravo Córdoba", "intereses": "Administración del conocimiento, Integración de información, Sistemas de información multimedia y georreferenciada"},
{"cargo": "Profesor Asociado", "name": "Rodrigo Cardoso Rodríguez", "intereses": "Métodos formales, Especificación, Verificación y pruebas de software, Educación en informática"},
{"cargo": "Profesor Asistente", "name": "Nicolás Cardozo Álvarez", "intereses": "Lenguajes de programación, Sistemas adaptativos, Análisis y Verificación dinámica de programas, Ingeniería de Software"},
{"cargo": "Profesora Titular", "name": "Rubby Casallas Gutiérrez", "intereses": "Desarrollo de software basado en modelos, Líneas de producto de software, Modelamiento de dominios específicos."},
{"cargo": "Instructor", "name": "Lina Casas", "intereses": "Planificación estratégica de TI, Arquitectura empresarial, Arquitecturas Orientadas a Servicios"},
{"cargo": "Profesor Asociado", "name": "Harold Castro Barrera", "intereses": "Computación de alto rendimiento, Sistemas distribuidos, Redes de comunicación"},
{"cargo": "Profesor Asociado", "name": "Darío Correal Torres", "intereses": "Desarrollo de software basado en modelos, Modelado de dominios específicos, Arquitecturas orientadas a servicios"},
{"cargo": "Profesor Asociado", "name": "Fernando de la Rosa Rosero", "intereses": "Robótica móvil y sistemas autónomos, Computación visual, Interacción humano-computador"},
{"cargo": "Profesor Asociado", "name": "Yezid Donoso Meisel", "intereses": "Optimización de redes, Calidad de servicio en redes, Seguridad de redes"},
{"cargo": "Profesor visitante", "name": "Jorge Duitama Castellanos", "intereses": "Bioinformática"},
{"cargo": "Profesor Asociado", "name": "Pablo Figueroa Forero", "intereses": "Desarrollo de videojuegos, Realidad virtual"},
{"cargo": "Instructor", "name": "César Forero González", "intereses": "Arquitectura de software, Ingeniería de software, Cloud Computing, Desarrollo Ágil"},
{"cargo": "Profesora Asistente", "name": "Kelly Garcés Pernett", "intereses": "Ingeniería basada en modelos, Lenguajes de dominio específico, Modernización y evolución de software"},
{"cargo": "Profesor Asociado", "name": "Rafael Gómez Díaz", "intereses": "Computación distribuida, Seguridad en dispositivos"},
{"cargo": "Instructor", "name": "Joshsua James González Díaz", "intereses": "Gestión de Incidentes de Seguridad, Ethical Hacking, Computación Forense, Aspectos Legales Informáticos"},
{"cargo": "Profesor Asistente", "name": "Óscar González Rojas", "intereses": "Gobierno de TI, Monitoreo y automatización de procesos de negocio, Arquitectura empresarial"},
{"cargo": "Profesora Asociada", "name": "Marcela Hernández Hoyos", "intereses": "Procesamiento de imágenes médicas"},
{"cargo": "Profesor Asociado", "name": "José Tiberio Hernández", "intereses": "Computación visual, Procesamiento y análisis de imágenes"},
{"cargo": "Profesor Asistente", "name": "Andrea Herrera Suescún", "intereses": "Tecnologías de Información y Comunicaciones (ICT), Capacidad de recuperación o resiliencia de las ICT, Cadenas de suministro de servicios de ICT y la gestión de riesgos de ICT. Áreas en exploración, específicamente, el papel de las ICT en la creación de cadenas de suministro más resilientes mediante el fomento de un aprendizaje colectivo en un entorno económico mundial cada vez más complejo."},
{"cargo": "Profesora Asociada", "name": "Claudia Jiménez Guarín", "intereses": "Sistemas Pervasive y adaptación al contexto, Big Data y Web 3.0, Computación móvil"},
{"cargo": "Profesor Asistente", "name": "Mario Linares Vásquez", "intereses": "Evolución y mantenimiento de software (énfasis en aplicaciones Android), Minería de repositorios de software, Generación automática de resúmenes de código, Pruebas automáticas de aplicaciones móviles"},
{"cargo": "Profesora Asociada", "name": "Olga Mariño Drews", "intereses": "Inteligencia artificial, Representación y gestión del conocimiento, E-learning"},
{"cargo": "Instructor", "name": "Jesse Padilla Agudelo", "intereses": "Infraestructura de Comunicaciones, Arquitectura de Infraestructura, Internet de las Cosas"},
{"cargo": "Instructor", "name": "Vanessa Pérez Romanello", "intereses": "Computación Visual, Procesamiento de imágenes"},
{"cargo": "Profesora Asistente", "name": "Sandra Rueda", "intereses": "Seguridad de redes y sistemas, Control de acceso obligatorio e integración de políticas de seguridad"},
{"cargo": "Profesor Asistente", "name": "Mario Sanchez", "intereses": "Planificación estratégica de TI, Arqutiectura empresarial, Diseño y desarrollo de Sistemas de Información"},
{"cargo": "Profesora Asociada", "name": "Silvia Takahashi Rodríguez", "intereses": "Diseño e implementación de lenguajes, Reingeniería de software, Semántica de lenguajes"},
{"cargo": "Profesor Asociado", "name": "Victor Toro Córdoba", "intereses": "Sistemas de información empresariales, Innovación y emprendiemiento con TI, Toma de decisiones en TI"},
{"cargo": "Profesor Asociado", "name": "Jorge Villalobos Salcedo", "intereses": "Arquitectura empresarial, Arquitecturas orientadas a servicios, Arquitectura de software"},
{"cargo": "Profesora Asociada", "name": "María del Pilar Villamil Giraldo", "intereses": "Minería de datos distribuida, Inteligencia de negocios (énfasis en el sector salud)"}

];